# Copyright IBM Corp. All Rights Reserved.

OrdererOrgs:

  - Name: Orderer
    Domain: bc4scm.de
  
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5


PeerOrgs:

  - Name: IBO
    Domain: ibo.bc4scm.de
    EnableNodeOUs: true

    Template:
      Count: 2

    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
